# config/elastic_apm.yml:

# Set the service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: <%= ENV.fetch('ELASTIC_APM_SERVICE_NAME') %>

# Use if APM Server requires a secret token
#secret_token: ''

# Set the custom APM Server URL (default: http://localhost:8200)
server_url: <%= ENV.fetch('ELASTIC_APM_SERVICE_URL') %>

# Set the service environment
environment: <%= ENV.fetch('ELASTIC_APM_ENVIRONMENT') %>
